In [36]:
!pwd

/Users/ronak/Documents/study


In [2]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"


In [30]:
import matplotlib.pyplot as plt
from sklearn import linear_model
import numpy as np
from sklearn.metrics import mean_squared_error, r2_score

In [4]:
reg = linear_model.LinearRegression()
ar = np.array([[[1],[2],[3],[4]], [[3],[6],[9],[12]]])
y = ar[1,:]
x = ar[0,:]

In [5]:
ar

array([[[ 1],
        [ 2],
        [ 3],
        [ 4]],

       [[ 3],
        [ 6],
        [ 9],
        [12]]])

In [6]:
y

array([[ 3],
       [ 6],
       [ 9],
       [12]])

In [5]:
x

array([[1.],
       [2.],
       [3.]])

In [17]:
reg.fit(x,y)
print('Coefficients: \n', reg.coef_)
xTest = np.array([[1],[2],[3],[4]])
ytest =  np.array([[3],[6],[9],[12]])

LinearRegression()

Coefficients: 
 [[3.]]


In [31]:
preds = xTest* 2

In [32]:
preds

array([[2],
       [4],
       [6],
       [8]])

In [33]:
# preds =np.array([[2],[4],[6],[8]])
# reg.predict(xTest)
print("R2 score : %.2f" % r2_score(ytest,preds))
print("Mean squared error: %.2f" % mean_squared_error(ytest,preds))

R2 score : 0.33
Mean squared error: 7.50


In [12]:
#total variance:
mean_y=np.mean(y)   
mean_y
total_variance=sum((y-mean_y)**2) # (y_i - y_mean)^2
total_variance
#sum(ytest*ytest)

7.5

array([45.])

In [34]:
#residuals
sum((ytest-preds)**2)

array([30])

Explained_variance?

In [ ]:
##either one of them
#(y_hat_i - y_mean)^2
#(y_hat_i - y_hat_mean)^2

In [35]:
mean_preds=np.mean(preds)   
sum((preds-mean_preds)**2)
sum((preds-mean_y)**2)

array([20.])

array([45.])

In [ ]:
#none of the above value equals 15!

as total variance is 45 and residauls are 30, the captured variacen should be 15.

5.0

In [28]:
preds
(preds-mean_preds)

array([[2],
       [4],
       [6],
       [8]])

array([[-3.],
       [-1.],
       [ 1.],
       [ 3.]])

In [26]:
# ytest-mean_y
sum((preds-mean_preds)**2)

array([20.])

In [29]:
sum((preds-mean_y)**2)

array([45.])

In [54]:
ytest

array([[ 9. ],
       [ 8.5],
       [14. ]])

In [13]:
preds = reg.predict(xTest)
g=(ytest-preds) **2
g
sum(g)
# y_val=ytest-np.mean(ytest)
# y_val

array([[ 1.],
       [ 4.],
       [ 9.],
       [16.]])

array([30.])

In [40]:
total_var=np.var(y)

In [29]:
rss=sum((xTest-preds)**2)

In [59]:
rss

array([79.22585833])

In [36]:
#residuals


9

In [32]:
1- (rss/total_variance)

array([-8.7563184])

In [60]:
res=ytest-preds
sum(res*res)

array([7.02085833])

In [44]:
total_var=np.var(y)
total_var

2.706822222222223

In [42]:
preds = reg.predict(x)
res_var=np.var(x-preds)
res_var

0.6868166666666662

In [46]:
1-res_var/total_var

0.7462645824952592

In [47]:
r2_score(y,preds)

0.9999979475727996

In [56]:
import matplotlib.pyplot as plt
from sklearn import linear_model
import numpy as np
from sklearn.metrics import mean_squared_error, r2_score

reg = linear_model.LinearRegression()
ar = np.array([[[1],[2],[3]], [[2.01],[4.03],[6.04]]])
y = ar[1,:]
x = ar[0,:]
reg.fit(x,y)
print('Coefficients: \n', reg.coef_)
xTest = np.array([[4],[5],[6]])
ytest =  np.array([[9],[8.5],[14]])

preds = reg.predict(xTest)
print("R2 score : %.2f" % r2_score(ytest,preds))
print("Mean squared error: %.2f" % mean_squared_error(ytest,preds))

Coefficients: 
 [[2.015]]
R2 score : 0.62
Mean squared error: 2.34


In [75]:
er = []
g = 0
for i in range(len(ytest)):
    print( "actual=", ytest[i], " observed=", preds[i])
    x = (ytest[i] - preds[i]) **2
    er.append(x)
    g = g + x
g    
# x = 0
# for i in range(len(er)):
#    x = x + er[i]

# print ("MSE", x / len(er))
er
v = np.var(er)
print ("variance", v)

print ("average of errors ", np.mean(er))

m = np.mean(ytest)
print ("average of observed values", m)

np.var(er)
np.var(ytest)
np.var(er)/np.var(ytest)
1-(np.var(er)/np.var(ytest))

y = 0
for i in range(len(ytest)):
    y = y + ((ytest[i] - m) ** 2)

print ("total sum of squares", y)
print ("ẗotal sum of residuals ", g)
# print ("r2 calculated", 1 - (g / y))

actual= [9.]  observed= [8.05666667]
actual= [8.5]  observed= [10.07166667]
actual= [14.]  observed= [12.08666667]


array([7.02085833])

[array([0.88987778]), array([2.47013611]), array([3.66084444])]

variance 1.2881398892129619
average of errors  2.3402861111111117
average of observed values 10.5


1.2881398892129619

6.166666666666667

0.2088875496021019

0.7911124503978981

total sum of squares [18.5]


In [81]:
g

array([7.02085833])

In [80]:
y

array([18.5])

In [83]:
1-g/y

array([0.62049414])